// Subtitle selection, split out from YtdlpManager so the language/format
// preference logic can be unit-tested without spawning yt-dlp.

export interface YtdlpSubtitle {
  url?: string;
  ext?: string;
  name?: string;
}

export interface SubtitleInfo {
  url: string;
  language: string;
  isAutoGenerated: boolean;
}

const PREFERRED_LANGUAGES = ['en', 'en-US', 'en-GB', 'en-orig'];

/**
 * Pick a single best subtitle entry from a language->entries map, preferring
 * VTT format. Tries preferred (English) languages first, then any language.
 */
function pickFromMap(
  subs: Record<string, YtdlpSubtitle[]> | undefined,
  isAutoGenerated: boolean
): SubtitleInfo | null {
  if (!subs) return null;

  const tryLang = (lang: string): SubtitleInfo | null => {
    const entries = subs[lang];
    if (!entries || entries.length === 0) return null;
    const vttEntry = entries.find(e => e.ext === 'vtt');
    const entry = vttEntry || entries[0];
    if (entry?.url) {
      return { url: entry.url, language: lang, isAutoGenerated };
    }
    return null;
  };

  // Preferred languages first
  for (const lang of PREFERRED_LANGUAGES) {
    const found = tryLang(lang);
    if (found) return found;
  }

  // Fall back to any available language
  for (const lang of Object.keys(subs)) {
    const found = tryLang(lang);
    if (found) return found;
  }

  return null;
}

/**
 * Choose the best available subtitle, preferring manually-authored subtitles
 * over auto-generated captions. Returns an array (0 or 1 entries) to match the
 * existing consumer shape.
 */
export function selectBestSubtitles(
  subtitles: Record<string, YtdlpSubtitle[]> | undefined,
  automaticCaptions: Record<string, YtdlpSubtitle[]> | undefined
): SubtitleInfo[] {
  const manual = pickFromMap(subtitles, false);
  if (manual) return [manual];

  const auto = pickFromMap(automaticCaptions, true);
  if (auto) return [auto];

  return [];
}
