import { selectBestSubtitles } from '../subtitleSelector';

describe('selectBestSubtitles', () => {
  it('returns an empty array when no subtitles are present', () => {
    expect(selectBestSubtitles(undefined, undefined)).toEqual([]);
    expect(selectBestSubtitles({}, {})).toEqual([]);
  });

  it('prefers manual subtitles over auto-generated captions', () => {
    const result = selectBestSubtitles(
      { en: [{ url: 'https://manual/en.vtt', ext: 'vtt' }] },
      { en: [{ url: 'https://auto/en.vtt', ext: 'vtt' }] }
    );

    expect(result).toEqual([
      { url: 'https://manual/en.vtt', language: 'en', isAutoGenerated: false },
    ]);
  });

  it('falls back to auto-generated captions when no manual subtitles exist', () => {
    const result = selectBestSubtitles(
      undefined,
      { en: [{ url: 'https://auto/en.vtt', ext: 'vtt' }] }
    );

    expect(result).toEqual([
      { url: 'https://auto/en.vtt', language: 'en', isAutoGenerated: true },
    ]);
  });

  it('prefers a preferred (English) language over others', () => {
    const result = selectBestSubtitles(
      {
        fr: [{ url: 'https://manual/fr.vtt', ext: 'vtt' }],
        en: [{ url: 'https://manual/en.vtt', ext: 'vtt' }],
      },
      undefined
    );

    expect(result[0]!.language).toBe('en');
  });

  it('prefers the VTT entry within a language', () => {
    const result = selectBestSubtitles(
      {
        en: [
          { url: 'https://manual/en.srv3', ext: 'srv3' },
          { url: 'https://manual/en.vtt', ext: 'vtt' },
        ],
      },
      undefined
    );

    expect(result[0]!.url).toBe('https://manual/en.vtt');
  });

  it('falls back to any language when no preferred language is available', () => {
    const result = selectBestSubtitles(
      { de: [{ url: 'https://manual/de.vtt', ext: 'vtt' }] },
      undefined
    );

    expect(result).toEqual([
      { url: 'https://manual/de.vtt', language: 'de', isAutoGenerated: false },
    ]);
  });

  it('uses the first entry when no VTT format is available', () => {
    const result = selectBestSubtitles(
      { en: [{ url: 'https://manual/en.srv3', ext: 'srv3' }] },
      undefined
    );

    expect(result[0]!.url).toBe('https://manual/en.srv3');
  });

  it('skips language entries that have no URL', () => {
    const result = selectBestSubtitles(
      { en: [{ ext: 'vtt' }] },
      { en: [{ url: 'https://auto/en.vtt', ext: 'vtt' }] }
    );

    // The manual 'en' entry has no url, so it falls through to auto captions
    expect(result).toEqual([
      { url: 'https://auto/en.vtt', language: 'en', isAutoGenerated: true },
    ]);
  });
});
